### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by Jyru-Ken** [Buttys/DevProLauncher#51]
The Simhei.ttf font hasn't got all the french characters we need for comprehensives texts cards. Please could you add in the next update the arial font, because it is the one we use before. Thank You.

**Comment by Buttys** [comment]
Do you have a back up of this font file Jyru-ken?

**Comment by Jyru-Ken** [comment]
Here is the font we want to use. But even if I put it into the font directory, the launcher options didn't list it :/

http://jyruken.free.fr/tools/msgothic.ttc
