### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by ghost** [Buttys/DevProLauncher#57]
hi,everybody
sorry.i dont use english very much.

i cant build devprolauncher!
i use visual studio 2010 express.
but i can not read YGOPro Launcher.csproj.

plaese tell me how to solve this problem.
thank you.

**Comment by Buttys** [comment]
Hey, do you have SP1 installed for vs2010? thats the only real problem i can think of
http://www.microsoft.com/en-us/download/details.aspx?id=23691

**Comment by ghost** [comment]
very thanks!!!!
i solved it!!!
i love you!!!
